### ISSUE TITLE
rare indicator not shown on non-elites

### ISSUE THREAD

**Issue by hollo6** [Luxocracy/TidyPlatesContinued#30]
Rare indicator is not shown on nameplates if the mob is not Elite (e.g. in expeditions). Could you please add it to those as well? Thanks!

**Comment by Luxocracy** [comment]
Hmm, thought all rares were also classified as elites... But this shouldn't be too hard to fix.

**Comment by Luxocracy** [comment]
Managed to figure out what it was, should be working properly now in the [latest release](https://github.com/Luxocracy/TidyPlatesContinued/releases/tag/6.21.9a)

**Comment by hollo6** [comment]
Using that version now, still the same. The indicator is there for elites but not for non-elites.

**Comment by hollo6** [comment]
Just checked in an expedition and I can't see it on any rares there either.
Is there anything I can do to debug why could this be happening?

**Comment by Luxocracy** [comment]
I would check that you are actually using the latest version, and that the Elite Icon widget is actually enabled (If you can't see it on any rares that is).

You could try to run this command while targeting a mob that is supposed to show up as rare.
`/run print(UnitClassification("target"))`

Which will print which type of mob it is (normal, elite, rare, etc). If it prints 'rare' or 'rareelite' it should be showing.

**Comment by hollo6** [comment]
I just realized it's a problem with the theme. I've been always using Quatre and never even installed the others, but now I've tried and all the other themes has the indicator but this one.

**Comment by Luxocracy** [comment]
It is actually how the theme is intended to be. It, as well as some others, use a border to signify elite/rare instead of a star.

**Comment by hollo6** [comment]
Is it possible to change the indicator on a theme? I found out that the only theme that fits my needs is Quatre and I'd like to see the golden/silver stars on it because I just can't see the border.

**Comment by Luxocracy** [comment]
You would have to edit the themes file yourself. Refer to [this](https://github.com/Luxocracy/TidyPlatesContinued/issues/27) for what is essentially needed.

**Comment by hollo6** [comment]
Awesome, did this and now everything is just like I wanted! Thank you!

**Comment by hollo6** [comment]
Not sure if it's intended or not, just noticed that the elite indicator is also present for bosses. I think it should be only one or the other.

**Comment by Luxocracy** [comment]
Hmm, I guess you are right. It's kind of unnecessary to have them be marked as an elite, when they are already marked as a boss.
