### ISSUE TITLE
Strange rotating debuff

### ISSUE THREAD

**Issue by ja0b** [Luxocracy/TidyPlatesContinued#38]
In the last version, I'm seeing a strange rotating debuff on the adds I hit.
![captured](https://user-images.githubusercontent.com/11311685/48318700-9478c300-e604-11e8-81e3-e3298431d4bf.PNG)

Any ideas ?

**Comment by Luxocracy** [comment]
No clue, someone else posted the exact same issue a few days ago. Apparently it was solved by re-downloading the files.

**Comment by ja0b** [comment]
I tried that a few times, I even installed the updater you have. Still seeing the same thing. I'll try to get more info about it.

**Comment by Luxocracy** [comment]
Try the [latest version](https://github.com/Luxocracy/TidyPlatesContinued/releases/tag/6.21.12) and see if this issue persists.

**Comment by ja0b** [comment]
The last release seems to fix this problem, what was it?

**Comment by Luxocracy** [comment]
Could have been because I changed how the repo handled file endings a few days ago. But I feel like that wouldn't have impacted the attached files of the releases. 

So I'm still not completely sure if me reverting that fixed it . Or if it was unrelated and there was some different issue all together.

**Comment by yishuangfrank** [comment]
I use a tool to check and download the addon.
